In [1]:
a = [1,3,2,3,7,2,1]

In [2]:
a[2]

2

In [3]:
a[-1]

1

In [4]:
a[::2]

[1, 2, 7, 1]

In [5]:
a[::-1]

[1, 2, 7, 3, 2, 3, 1]

In [6]:
a[::-2]

[1, 7, 2, 1]

In [7]:
for i in range(2, len(a)):
    if (a[i]%3 == 0 and a[i] < 5):
        print(a[i])

3


In [8]:
string = str(input())
stringArray = string.split(' ')
print(stringArray[-1])

Abra babra cadabra
cadabra


In [9]:
string = str(input())

if (string == string[::-1]):
    print("YES")
else:
    print("NO")

kazak
YES


In [10]:
string = str(input())
stringArray = string.split(' ')
stringArray

hello kirill how are you


['hello', 'kirill', 'how', 'are', 'you']

In [11]:
str1 = "abcDEFabcgh"
str2 = "abc"
str3 = "XYZ"
str1.replace(str2, str3)

'XYZDEFXYZgh'

In [12]:
import numpy as np

In [13]:
a = np.array([1, 2, 3])

In [14]:
mat = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
a.shape

(3,)

In [16]:
mat.shape

(2, 3)

In [17]:
z = np.zeros((3,))
z

array([0., 0., 0.])

In [18]:
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [20]:
np.arange(2.4, 17.3, 0.7)

array([ 2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,  8. ,  8.7,  9.4,
       10.1, 10.8, 11.5, 12.2, 12.9, 13.6, 14.3, 15. , 15.7, 16.4, 17.1])

In [21]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
A = np.arange(8).reshape(2, -1)

In [23]:
A.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [24]:
A = np.arange(6).reshape(2, -1)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [26]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [27]:
np.concatenate((A, A**2), axis=1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [61]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [63]:
A * 1.0 / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [64]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [66]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [67]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [68]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [76]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
A.min()

0

In [39]:
A.sum(axis=1)#строки

array([ 3, 12, 21])

In [75]:
A.mean(axis=0)#столбцы

array([3., 4., 5.])

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[2:5]

array([2, 3, 4])

In [42]:
a[3:8:2]

array([3, 5, 7])

In [43]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [44]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [45]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [46]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [47]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

In [48]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [50]:
A[(A % 5 != 3) & (A < 6)]

array([0, 1, 2, 4, 5])

In [51]:
a = [5,3,1,7,2,3,4,3]

In [52]:
np.sort(a)

array([1, 2, 3, 3, 3, 4, 5, 7])

In [54]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
np.split(a, [2, 7])

[array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8, 9])]